# Generated by Django 3.2.9 on 2021-12-02 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category_image', models.ImageField(default='', upload_to='assets/category/')),
            ],
        ),
        migrations.CreateModel(
            name='MenuElements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_field', models.FileField(default='', upload_to='assets/img/')),
                ('name', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(null=True)),
                ('finish_date', models.DateTimeField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.category')),
            ],
        ),
        migrations.CreateModel(
            name='OtherElements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=500)),
                ('menuElements', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.menuelements')),
            ],
        ),
    ]
