# Generated by Django 3.2.9 on 2022-01-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0002_alter_menuelements_file_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuelements',
            name='file_field',
            field=models.FileField(default='', upload_to='assets/img/'),
        ),
    ]
