# Generated by Django 3.2.9 on 2021-12-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0008_auto_20211201_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuelements',
            name='image',
            field=models.ImageField(upload_to='assets/img/'),
        ),
    ]
