# Generated by Django 3.2.9 on 2021-12-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0009_alter_menuelements_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuelements',
            name='image',
        ),
        migrations.AddField(
            model_name='menuelements',
            name='file_field',
            field=models.FileField(default=True, upload_to='assets/img/'),
        ),
    ]
