# Generated by Django 3.2.9 on 2021-12-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0010_auto_20211201_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuelements',
            name='file_field',
            field=models.FileField(default='', upload_to='assets/img/'),
        ),
    ]
